### ISSUE TITLE
Feature request: Multiple sharedprefs

### ISSUE THREAD

**Issue by evowizz** [aaabidunique/android-utility#1]
Hi, I think it would be great to be able to create multiple sharedprefs files with different name in the same class :)

**Comment by aaabidunique** [comment]
Thata still possible if you assign diiferent file name before accessing its method, though i will find a better way to that. Btw if u have any idea just let me know.

**Comment by evowizz** [comment]
@aaabidunique Sorry I forget to answer, well if I have other ideas I will contact you, thanks :)

**Comment by aaabidunique** [comment]
@EvoWizz Ideas and feedback are always welcome.

**Comment by evowizz** [comment]
@aaabidunique Thanks again :)
