### ISSUE TITLE
Error while building (android:allowbackup)

### ISSUE THREAD

**Issue by evowizz** [aaabidunique/android-utility#2]
Could you please remove the line "android:allowBackup="true" " in your Android Manifest please?
Explanation: When our application has the same bool value (true), then there is no problem, but when your manifest has "true" and our app has "false" (or false / true) then there is a conflict, and we have to add this line: "tools:replace="android:allowBackup" " to replace your value. But if you directly remove the line, there won't be any conflict :)

**Comment by aaabidunique** [comment]
@EvoWizz Thanks for pointing out.Since I was not facing any problem with my app so I kept the default setting.I have updated the androidManifest.xml as you asked with this a5c603c.

**Comment by evowizz** [comment]
@aaabidunique Thanks! :)
